# Generated by Django 5.2.1 on 2025-05-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_skill_bonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['created_at'], 'verbose_name': 'Jogador', 'verbose_name_plural': 'Jogadores'},
        ),
    ]
